apiVersion: v1
kind: Pod
metadata:
  name: dev-services
  labels:
    app: postgres
    environment: development
spec:
  containers:
  - name: postgres
    image: postgres:14.7
    env:
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_USER
      value: root
    - name: POSTGRES_PASSWORD
      value: ""
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    ports:
    - containerPort: 5432
      hostPort: 5432
      hostIP: 127.0.0.1
      protocol: TCP
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
    - name: init-scripts
      mountPath: /docker-entrypoint-initdb.d
      readOnly: true
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-data
  - name: init-scripts
    hostPath:
      path: /Users/mikevive/dev/services/postgres/init-scripts
      type: Directory
